#!/bin/bash
set -e

## Bootstrap passwordless sudo. Every later `sudo` in this script - and
## teslabot/bt_server.py at runtime, launched by systemd with no TTY - assumes
## this already works, so it has to happen first and has to actually succeed.
## `sudo echo foo >> /etc/sudoers` is a classic trap: the `>>` redirect runs in
## this unprivileged shell, not under sudo, so it silently fails to write to a
## root-owned file. Writing through `sudo tee` avoids that, and `visudo -c`
## catches a syntax mistake before it can lock out sudo entirely.
if ! sudo -n true 2>/dev/null; then
  read -s -p "sudo password for $(whoami) (used once, to set up passwordless sudo): " SUDO_PW
  echo
  echo "$SUDO_PW" | sudo -S true
fi
echo "pi ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/010-pi-nopasswd > /dev/null
sudo chmod 440 /etc/sudoers.d/010-pi-nopasswd
sudo visudo -c

## Install the required packages and dependencies.
## python3-setuptools: needed to build the rpi-rgb-led-matrix Python bindings
##   (their setup.py uses the setuptools-compatible API - distutils itself was
##   removed in Python 3.12+, which is what current Raspberry Pi OS ships).
## python3-bluez: the apt package for pybluez - `pip install pybluez` refuses
##   to run on this system (PEP 668 "externally managed environment"), and
##   fighting that with --break-system-packages is worse than just using the
##   real Debian package.
## cython3, python3-pil: rgbmatrix's Python bindings need both - see below.
sudo apt-get update
sudo apt-get install -y python3-pip python3-dev libpython3-dev \
  python3-setuptools bluetooth libbluetooth-dev bluez-tools python3-bluez \
  cython3 python3-pil
sudo raspi-config nonint do_wifi_country FR

## Compile the C++ library for the LED matrix, plus the Python bindings.
## bt_server.py imports directly (rgbmatrix) - this drives the panel through
## the library's own frame buffer instead of shelling out to a compiled demo
## binary per image, which is what makes updates flicker-free.
##
## The bindings' core.cpp/graphics.cpp are Cython output, not hand-written -
## regenerate them from the actual source (core.pyx/graphics.pyx) instead of
## trusting whatever was last committed. A committed-and-forgotten generated
## file is exactly how this broke in the first place: it was generated by an
## old Cython against an old CPython's ABI, and silently stopped compiling
## the moment this Pi's Python (3.13) removed the internals it poked at
## directly. Regenerating against whatever Cython/Python is actually on the
## machine doing the build sidesteps that class of bug entirely.
cd /home/pi/rpi-rgb-led-matrix/bindings/python/rgbmatrix
cython3 --cplus -I . core.pyx
cython3 --cplus -I . graphics.pyx
cd /home/pi
make -C /home/pi/rpi-rgb-led-matrix/
make -C /home/pi/rpi-rgb-led-matrix/bindings/python build-python PYTHON=$(which python3)
sudo make -C /home/pi/rpi-rgb-led-matrix/bindings/python install-python PYTHON=$(which python3)

sudo mv conf/dbus-org.bluez.service /etc/systemd/system/
sudo mv conf/teslabot.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl restart bluetooth
sudo systemctl enable teslabot.service
sudo systemctl start teslabot.service
sudo sdptool add SP

rm -f /home/pi/deploy.sh
