#!/bin/bash

function activate_bluetooth() {
    while true; do
        bluetoothctl power on
        bluetoothctl discoverable on
        sleep 5
    done
}

function keep_pairing_agent_registered() {
    while true; do
        sudo bt-agent -c NoInputNoOutput
        echo 'Pairing agent exited, restarting...' >&2
        sleep 1
    done
}

activate_bluetooth &
keep_pairing_agent_registered &

while true; do
    echo "Tesla Bot server starting..."
    sudo python /home/pi/bt_server.py
    echo "Tesla Bot server returned exit code $?. Respawning..." >&2
    sleep 1
done
